# Generated by Django 5.0.4 on 2026-04-23 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperationalIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("Activated", "Activated"),
                            ("Nonconforming", "Nonconforming"),
                            ("Contingent", "Contingent"),
                        ],
                        default="Accepted",
                        max_length=20,
                    ),
                ),
                (
                    "uss_base_url",
                    models.URLField(
                        help_text="URL base da USS responsável por esta OIR."
                    ),
                ),
                (
                    "dss_id",
                    models.CharField(
                        blank=True,
                        help_text="ID da OIR conforme registrado no DSS.",
                        max_length=255,
                    ),
                ),
                (
                    "dss_ovn",
                    models.CharField(
                        blank=True,
                        help_text="OVN (Operational Version Number) retornado pelo DSS.",
                        max_length=255,
                    ),
                ),
                (
                    "extents",
                    models.JSONField(
                        help_text="Lista de volumes 4D — [{'volume': {...}, 'time_start': {...}, 'time_end': {...}}]"
                    ),
                ),
                (
                    "dss_response",
                    models.JSONField(
                        blank=True,
                        help_text="Resposta completa recebida do DSS na última submissão.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Operational Intent",
                "verbose_name_plural": "Operational Intents",
                "ordering": ["-created_at"],
            },
        ),
    ]
