# Generated by Django 5.2.13 on 2026-04-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oir", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalintent",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Prioridade da operação. Valores maiores = maior prioridade.",
            ),
        ),
    ]
