# Generated by Django 5.0.4 on 2026-04-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oir", "0002_operationalintent_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalintent",
            name="subscription_id",
            field=models.CharField(
                blank=True,
                help_text="ID da subscrição DSS associada a esta OIR.",
                max_length=255,
                null=True,
            ),
        ),
    ]
