# Generated by Django 5.0.4 on 2026-05-04 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oir", "0003_add_subscription_id_to_operationalintent"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentificationServiceArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dss_id", models.CharField(blank=True, max_length=255)),
                ("uss_base_url", models.URLField(blank=True)),
                (
                    "extents",
                    models.JSONField(
                        help_text="{'volume':{...}, 'time_start':{...}, 'time_end':{...}}"
                    ),
                ),
                ("last_notification", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operational_intent",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="isa",
                        to="oir.operationalintent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identification Service Area",
                "ordering": ["-created_at"],
            },
        ),
    ]
