# Generated by Django 5.0.4 on 2026-05-05 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oir", "0004_add_identification_service_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="identificationservicearea",
            name="dss_version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="identificationservicearea",
            name="dss_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="identificationservicearea",
            name="extents",
            field=models.JSONField(help_text="Volume 4D (ASTM F3411) do ISA"),
        ),
        migrations.AlterField(
            model_name="identificationservicearea",
            name="operational_intent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="isas",
                to="oir.operationalintent",
            ),
        ),
        migrations.AlterField(
            model_name="identificationservicearea",
            name="uss_base_url",
            field=models.URLField(),
        ),
    ]
