# Generated by Django 5.0.4 on 2026-05-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oir", "0005_add_isa_dss_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="RIDTelemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("alt", models.FloatField(default=-1000)),
                ("pressure_altitude", models.FloatField(default=-1000)),
                ("accuracy_h", models.CharField(default="HAUnknown", max_length=20)),
                ("accuracy_v", models.CharField(default="VAUnknown", max_length=20)),
                ("track", models.FloatField(default=361)),
                ("speed", models.FloatField(default=255)),
                (
                    "speed_accuracy",
                    models.CharField(default="SAUnknown", max_length=20),
                ),
                ("vertical_speed", models.FloatField(default=63)),
                (
                    "operational_status",
                    models.CharField(default="Undeclared", max_length=50),
                ),
                ("extrapolated", models.BooleanField(default=False)),
                ("height_distance", models.FloatField(default=0)),
                (
                    "height_reference",
                    models.CharField(default="GroundLevel", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "isa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry",
                        to="oir.identificationservicearea",
                    ),
                ),
            ],
            options={
                "verbose_name": "RID Telemetry",
                "ordering": ["-timestamp"],
            },
        ),
    ]
