# Generated by Django 5.0.4 on 2026-05-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oir", "0006_ridtelemetry"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalintent",
            name="nonconforming_since",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp do início do estado Nonconforming. Usado para contagem dos 60s.",
                null=True,
            ),
        ),
    ]
