# Generated by Django 5.0.4 on 2026-04-18 21:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlightPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("ACTIVATED", "Activated"),
                            ("NONCONFORMING", "Nonconforming"),
                            ("CONTINGENT", "Contingent"),
                            ("PLANNING", "Planning"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "volume",
                    django.contrib.gis.db.models.fields.GeometryField(dim=3, srid=4326),
                ),
                ("uss_base_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="OperationalIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dss_id", models.CharField(blank=True, max_length=255)),
                ("version", models.IntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("ACTIVATED", "Activated"),
                            ("NONCONFORMING", "Nonconforming"),
                            ("CONTINGENT", "Contingent"),
                            ("PLANNING", "Planning"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ovn", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "flight_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_intent",
                        to="flight_plans.flightplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalIntentConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conflict_dss_id", models.CharField(max_length=255)),
                ("conflict_uss_base_url", models.URLField()),
                (
                    "conflict_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "my_intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="flight_plans.operationalintent",
                    ),
                ),
            ],
            options={
                "unique_together": {("my_intent", "conflict_dss_id")},
            },
        ),
    ]
