# Generated by Django 5.0.4 on 2026-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalintent",
            name="subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
