# Generated by Django 5.0.4 on 2026-04-23 19:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_plans", "0002_operationalintent_subscription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightplan",
            name="astm_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flightplan",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="flightplan",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
